/*
BACKUP DATABASE [BU_Metrolog] TO  DISK = N'E:\DB_Backup\SQL\BU_backup.bak' WITH  COPY_ONLY, NOFORMAT, INIT,  NAME = N'BU_Metrolog-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
*/

USE [master]
RESTORE DATABASE [TST_BU_forIT] FROM  DISK = N'E:\DB_Backup\SQL\bu_backup.bak' WITH  FILE = 1,  MOVE N'BU_METROLOG' TO N'E:\MSSQL13.MSSQLSERVER\MSSQL\DATA\TST_BU_forIT.mdf',  MOVE N'BU_METROLOG_log' TO N'G:\MSSQL13.MSSQLSERVER\MSSQL\Log\TST_BU_forIT_log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5
GO
