/*
BACKUP DATABASE [ZUP_Metrolog] TO  DISK = N'E:\DB_Backup\SQL\ZUP_backup.bak' WITH  COPY_ONLY, NOFORMAT, INIT,  NAME = N'ZUP_Metrolog-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
*/

USE [master]
RESTORE DATABASE [TST_ZUP_forBuh] FROM  DISK = N'E:\DB_Backup\SQL\ZUP_backup.bak' WITH  FILE = 1,  MOVE N'ZUP_METROLOG' TO N'E:\MSSQL13.MSSQLSERVER\MSSQL\DATA\TST_ZUP_forBuh.mdf',  MOVE N'ZUP_METROLOG_log' TO N'G:\MSSQL13.MSSQLSERVER\MSSQL\Log\TST_ZUP_forBuh_log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5
GO